#!/usr/bin/env python
# coding: utf-8

"""
plot_loss.py — Publication-Quality Learning Curve Visualizer
Reads raw training history JSON files generated by models (*_history.json)
and generates high-resolution comparison and diagnosis plots.

Usage Examples:
  # Plot a single model (e.g. Model 01)
  python plot_loss.py --model 01

  # Plot specific seed (e.g. Seed 42)
  python plot_loss.py --model 01 --seed 42

  # Plot all available models
  python plot_loss.py --all

  # Compare multiple architectures on the same graph
  python plot_loss.py --compare 01 05 13 17 --metric val_loss
"""

import os
import sys
import glob
import json
import argparse
import numpy as np

# Ensure headless compatibility on Linux/HPC
import matplotlib
if "--show" not in sys.argv:
    matplotlib.use("Agg")
import matplotlib.pyplot as plt

def load_history(filepath):
    with open(filepath, "r", encoding="utf-8") as fp:
        return json.load(fp)

def find_history_file(model_identifier, search_dir="."):
    if os.path.isfile(model_identifier):
        return model_identifier
    
    # Match by prefix (e.g. '01', '05') or full name
    matches = sorted(glob.glob(os.path.join(search_dir, f"{model_identifier}*_results.json")))
    if not matches:
        matches = sorted(glob.glob(os.path.join(search_dir, f"{model_identifier}*_history.json")))
    if not matches:
        matches = sorted(glob.glob(os.path.join(search_dir, f"{model_identifier}*.json")))
    if matches:
        return matches[0]
    return None

def plot_single_model(history_file, seed_choice="all", out_dir="plots", dpi=300):
    os.makedirs(out_dir, exist_ok=True)
    data = load_history(history_file)
    model_name = data.get("model_name", os.path.basename(history_file).replace("_results.json", "").replace("_history.json", ""))
    seeds_data = data.get("seeds", {})
    
    if not seeds_data:
        print(f"[Warning] No seed data found in {history_file}")
        return
        
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6), dpi=dpi)
    fig.suptitle(f"Learning Curves: {model_name}", fontsize=15, fontweight="bold")
    
    colors = plt.cm.tab10(np.linspace(0, 1, max(len(seeds_data), 10)))
    
    all_train_losses = []
    all_val_losses = []
    max_epochs = 0
    
    # 1. Plot Individual Seed Curves
    for idx, (seed, sdata) in enumerate(seeds_data.items()):
        if seed_choice != "all" and str(seed) != str(seed_choice):
            continue
            
        epochs = sdata.get("epochs", [])
        train_loss = sdata.get("train_loss", [])
        val_loss = sdata.get("val_loss", [])
        best_epoch = sdata.get("best_epoch", None)
        best_val = sdata.get("best_val_loss", None)
        
        all_train_losses.append(train_loss)
        all_val_losses.append(val_loss)
        max_epochs = max(max_epochs, len(epochs))
        
        c = colors[idx % len(colors)]
        ax1.plot(epochs, train_loss, label=f"Seed {seed} (Train)", color=c, alpha=0.4, linestyle="--")
        ax1.plot(epochs, val_loss, label=f"Seed {seed} (Val)", color=c, linewidth=1.5)
        
        if best_epoch:
            ax1.scatter([best_epoch], [best_val], color=c, s=40, zorder=5)
            
    ax1.set_title("Train vs. Val Loss Across Seeds", fontsize=12, fontweight="bold")
    ax1.set_xlabel("Epoch", fontsize=11)
    ax1.set_ylabel("MSE Loss", fontsize=11)
    ax1.grid(True, linestyle=":", alpha=0.6)
    if len(seeds_data) <= 5 or seed_choice != "all":
        ax1.legend(loc="upper right", fontsize=8)
        
    # 2. Plot Aggregate Mean ± Std Ribbon
    if all_val_losses:
        padded_train = np.full((len(all_train_losses), max_epochs), np.nan)
        padded_val = np.full((len(all_val_losses), max_epochs), np.nan)
        
        for i, t in enumerate(all_train_losses):
            padded_train[i, :len(t)] = t
        for i, v in enumerate(all_val_losses):
            padded_val[i, :len(v)] = v
            
        mean_train = np.nanmean(padded_train, axis=0)
        std_train  = np.nanstd(padded_train, axis=0)
        mean_val   = np.nanmean(padded_val, axis=0)
        std_val    = np.nanstd(padded_val, axis=0)
        epochs_arr = np.arange(1, max_epochs + 1)
        
        ax2.plot(epochs_arr, mean_train, label="Train Loss (Mean)", color="#1f77b4", linewidth=2)
        ax2.fill_between(epochs_arr, mean_train - std_train, mean_train + std_train, color="#1f77b4", alpha=0.2)
        
        ax2.plot(epochs_arr, mean_val, label="Val Loss (Mean)", color="#d62728", linewidth=2)
        ax2.fill_between(epochs_arr, mean_val - std_val, mean_val + std_val, color="#d62728", alpha=0.2)
        
        min_val_idx = np.nanargmin(mean_val)
        ax2.axvline(x=epochs_arr[min_val_idx], color="green", linestyle=":", linewidth=1.5,
                    label=f"Min Mean Val ({mean_val[min_val_idx]:.5f} @ Ep {epochs_arr[min_val_idx]})")
        
    ax2.set_title("Aggregate Convergence (Mean ± 1 Std Ribbon)", fontsize=12, fontweight="bold")
    ax2.set_xlabel("Epoch", fontsize=11)
    ax2.set_ylabel("MSE Loss", fontsize=11)
    ax2.grid(True, linestyle=":", alpha=0.6)
    ax2.legend(loc="upper right", fontsize=10)
    
    plt.tight_layout()
    out_file = os.path.join(out_dir, f"{model_name}_loss_curves.png")
    plt.savefig(out_file, dpi=dpi, bbox_inches="tight")
    plt.close()
    print(f"[Saved] Single model plot -> {out_file}")

def plot_comparison(model_identifiers, metric="val_loss", out_dir="plots", dpi=300):
    os.makedirs(out_dir, exist_ok=True)
    plt.figure(figsize=(10, 6), dpi=dpi)
    
    palette = plt.cm.tab10(np.linspace(0, 1, max(len(model_identifiers), 10)))
    
    for idx, mid in enumerate(model_identifiers):
        hfile = find_history_file(mid)
        if not hfile:
            print(f"[Warning] History file for '{mid}' not found. Skipping.")
            continue
            
        data = load_history(hfile)
        model_name = data.get("model_name", os.path.basename(hfile).replace("_history.json", ""))
        seeds_data = data.get("seeds", {})
        
        all_metric = []
        max_ep = 0
        for s, sdata in seeds_data.items():
            vals = sdata.get(metric, [])
            all_metric.append(vals)
            max_ep = max(max_ep, len(vals))
            
        if not all_metric:
            continue
            
        padded = np.full((len(all_metric), max_ep), np.nan)
        for i, m in enumerate(all_metric):
            padded[i, :len(m)] = m
            
        mean_vals = np.nanmean(padded, axis=0)
        std_vals  = np.nanstd(padded, axis=0)
        ep_arr    = np.arange(1, max_ep + 1)
        
        c = palette[idx % len(palette)]
        short_name = model_name.split("_baseline")[0].replace("_pytorch", "")
        plt.plot(ep_arr, mean_vals, label=f"{short_name} (min: {np.nanmin(mean_vals):.5f})", color=c, linewidth=2)
        plt.fill_between(ep_arr, mean_vals - std_vals, mean_vals + std_vals, color=c, alpha=0.15)
        
    plt.title(f"Model Architecture Convergence Comparison ({metric.replace('_', ' ').title()})", fontsize=13, fontweight="bold")
    plt.xlabel("Epoch", fontsize=11)
    plt.ylabel("MSE Loss", fontsize=11)
    plt.grid(True, linestyle=":", alpha=0.6)
    plt.legend(loc="upper right", fontsize=9)
    
    out_file = os.path.join(out_dir, "model_architecture_comparison.png")
    plt.tight_layout()
    plt.savefig(out_file, dpi=dpi, bbox_inches="tight")
    plt.close()
    print(f"[Saved] Multi-model comparison plot -> {out_file}")

def plot_horizon_degradation(model_identifiers, out_dir="plots", dpi=300):
    os.makedirs(out_dir, exist_ok=True)
    plt.figure(figsize=(12, 6), dpi=dpi)
    palette = plt.cm.tab10(np.linspace(0, 1, max(len(model_identifiers), 10)))
    
    for idx, mid in enumerate(model_identifiers):
        hfile = find_history_file(mid)
        if not hfile:
            print(f"[Warning] History file for '{mid}' not found. Skipping.")
            continue
            
        data = load_history(hfile)
        model_name = data.get("model_name", os.path.basename(hfile).replace("_results.json", ""))
        summary = data.get("summary", {})
        mean_mae_48 = summary.get("mean_mae_by_step_48")
        
        if not mean_mae_48:
            seeds = data.get("seeds", {})
            for s, sdata in seeds.items():
                s48 = sdata.get("step_48_metrics", {}).get("mae")
                if s48:
                    mean_mae_48 = s48
                    break
                    
        if not mean_mae_48:
            print(f"[Notice] No 48-step metrics found for '{mid}'. Skipping.")
            continue
            
        hours = np.arange(1, len(mean_mae_48) + 1) * 0.5  # 30 min per step -> hours
        c = palette[idx % len(palette)]
        short_name = model_name.split("_baseline")[0].replace("_pytorch", "")
        plt.plot(hours, mean_mae_48, label=f"{short_name} (24h MAE: {mean_mae_48[-1]:.4f} kW)", color=c, linewidth=2)
        
    plt.title("Forecast Horizon Error Degradation (24-Hour Horizon)", fontsize=13, fontweight="bold")
    plt.xlabel("Forecast Horizon (Hours)", fontsize=11)
    plt.ylabel("MAE (kW)", fontsize=11)
    plt.grid(True, linestyle=":", alpha=0.6)
    plt.xticks(np.arange(2, 25, 2))
    plt.legend(loc="upper left", fontsize=9)
    
    out_file = os.path.join(out_dir, "horizon_error_degradation.png")
    plt.tight_layout()
    plt.savefig(out_file, dpi=dpi, bbox_inches="tight")
    plt.close()
    print(f"[Saved] Horizon degradation plot -> {out_file}")

def find_predictions_file(model_identifier, search_dir="."):
    if os.path.isfile(model_identifier) and model_identifier.endswith(".npz"):
        return model_identifier
    matches = sorted(glob.glob(os.path.join(search_dir, f"{model_identifier}*_predictions.npz")))
    if matches:
        return matches[0]
    return None

def plot_load_profile(model_identifier, step=0, n_points=336, out_dir="plots", dpi=300):
    os.makedirs(out_dir, exist_ok=True)
    npz_file = find_predictions_file(model_identifier)
    if not npz_file:
        print(f"[Error] Could not find predictions .npz file for '{model_identifier}'.")
        print("Run the model first to generate its *_predictions.npz file.")
        return

    data = np.load(npz_file)
    y_true = data.get("y_true")
    pred_mean = data.get("pred_mean")
    pred_std = data.get("pred_std", None)

    if y_true is None or pred_mean is None:
        print(f"[Error] 'y_true' or 'pred_mean' missing in {npz_file}.")
        return

    step = min(max(0, step), y_true.shape[1] - 1)
    n_points = min(n_points, len(y_true))
    time_idx = np.arange(n_points) * 0.5  # half-hourly in hours

    actual_slice = y_true[:n_points, step]
    mean_slice   = pred_mean[:n_points, step]
    std_slice    = pred_std[:n_points, step] if pred_std is not None else np.zeros_like(mean_slice)

    plt.figure(figsize=(14, 6), dpi=dpi)
    plt.plot(time_idx, actual_slice, label="Actual Load (kW)", color="#222222", linewidth=1.8, alpha=0.9)
    plt.plot(time_idx, mean_slice, label=f"Ensemble Forecast (Mean @ Step {step})", color="#1f77b4", linewidth=1.8)
    if pred_std is not None:
        plt.fill_between(time_idx, np.maximum(0, mean_slice - std_slice), mean_slice + std_slice,
                         color="#1f77b4", alpha=0.25, label="Seed Uncertainty (±1 Std)")

    step_min = (step + 1) * 30
    plt.title(f"EV Aggregate Station Load Forecast: {os.path.basename(npz_file).replace('_predictions.npz', '')} [Horizon +{step_min} min]",
              fontsize=13, fontweight="bold")
    plt.xlabel("Timeline (Hours / 7-Day Window)", fontsize=11)
    plt.ylabel("Station Load (kW)", fontsize=11)
    plt.grid(True, linestyle=":", alpha=0.6)
    plt.legend(loc="upper right", fontsize=10)

    out_file = os.path.join(out_dir, f"{os.path.basename(npz_file).replace('_predictions.npz', '')}_profile_step{step}.png")
    plt.tight_layout()
    plt.savefig(out_file, dpi=dpi, bbox_inches="tight")
    plt.close()
    print(f"[Saved] Load profile plot -> {out_file}")

def main():
    parser = argparse.ArgumentParser(description="Publication Learning Curve Visualizer")
    parser.add_argument("--model", type=str, help="Model ID or filename (e.g. '01', '01_tfm_tfm_pytorch')")
    parser.add_argument("--seed", type=str, default="all", help="Seed ID or 'all' (default: all)")
    parser.add_argument("--all", action="store_true", help="Plot all available *_results.json files")
    parser.add_argument("--compare", nargs="+", help="Compare multiple model IDs (e.g. --compare 01 05 13 17)")
    parser.add_argument("--horizon", action="store_true", help="Plot 48-step horizon error degradation curve across models")
    parser.add_argument("--profile", action="store_true", help="Plot Actual vs Predicted Load Profile curve (with uncertainty ribbon)")
    parser.add_argument("--profile-step", type=int, default=0, help="Horizon step index to plot (0=30m, 5=3h, 11=6h, 47=24h, default: 0)")
    parser.add_argument("--profile-points", type=int, default=336, help="Number of half-hourly time steps to display (default: 336 = 7 days)")
    parser.add_argument("--metric", type=str, default="val_loss", choices=["val_loss", "train_loss"], help="Metric to compare")
    parser.add_argument("--out-dir", type=str, default="plots", help="Output directory (default: plots)")
    parser.add_argument("--dpi", type=int, default=300, help="DPI resolution (default: 300)")
    parser.add_argument("--show", action="store_true", help="Display plot interactively (GUI)")
    
    args = parser.parse_args()
    
    if args.profile and args.model:
        plot_load_profile(args.model, step=args.profile_step, n_points=args.profile_points, out_dir=args.out_dir, dpi=args.dpi)
    elif args.horizon and args.compare:
        plot_horizon_degradation(args.compare, out_dir=args.out_dir, dpi=args.dpi)
    elif args.compare:
        plot_comparison(args.compare, metric=args.metric, out_dir=args.out_dir, dpi=args.dpi)
    elif args.all:
        files = sorted(glob.glob("*_results.json"))
        if not files:
            files = sorted(glob.glob("*_history.json"))
        if not files:
            print("[Notice] No *_results.json or *_history.json files found in the current directory yet.")
            print("Run any model (e.g. python 01_tfm_tfm_pytorch.py) to generate results data.")
            return
        for f in files:
            plot_single_model(f, seed_choice=args.seed, out_dir=args.out_dir, dpi=args.dpi)
    elif args.model:
        hfile = find_history_file(args.model)
        if not hfile:
            print(f"[Error] Could not find results or history file for '{args.model}'.")
            print("Make sure the model has been run to generate its *_results.json file.")
            sys.exit(1)
        plot_single_model(hfile, seed_choice=args.seed, out_dir=args.out_dir, dpi=args.dpi)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
